# Generated by Django 4.1.7 on 2023-05-10 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
        ('raca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('idade', models.IntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raca.raca')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meu_dono', to='tutor.tutor')),
            ],
            options={
                'db_table': 'pet',
            },
        ),
    ]
